apps/app/src/styles.scss, apps/app/tailwind.config.js
Fixes # 37: Add project style to tailwind config
=> Tailwind config

.github/workflows/cd-dev.yml, .github/workflows/cd-prod.yml, .github/workflows/ci-prod.yml, apps/api/build.gradle, apps/api/src/main/java/com/fridgetoplate/api/HelloController.java
Continous deployment added for Angular application.
Fixes #12
=> Setup Workflows CD

apps/app/tailwind.config.js, libs/app/create/feature/src/create.page.html
Responsiveness to the create recipe page for mobile, tablet, deskop viewports
=> 56 create responsive design

libs/app/create/feature/src/create.page.html
Create responsive design implemented.
Fixes #56
=> Create Responsive Design (Updated)

.github/workflows/cd-dev.yml, .github/workflows/cd-prod.yml, apps/api/build.gradle, apps/api/src/main/resources/application.properties
Added CD for API to elastic beanstalk.
Fixes #13
=> Setup API CD Workflow

.github/workflows/cd-dev.yml, .github/workflows/cd-prod.yml
Fixed errors for zipping in workflow action.
Fixes #13
=> 💚 (workflows) Fixed Zipping Error

.github/workflows/ci-dev.yml, .github/workflows/ci-prod.yml, package.json, tools/coverageMerger.js
Full application testing and code coverage reporting.
Fixes #75
=> Workspace CI and Coverage

.github/workflows/ci-dev.yml, .github/workflows/ci-prod.yml, package.json
=> Workflows patch

libs/app/create/feature/src/create.page.spec.ts, libs/app/create/feature/src/create.page.ts
Fixed failing tests and added more test coverage
=> ✅ (app) : updated Create test coverage

libs/app/auth/data-access/src/auth.api.spec.ts, libs/app/auth/data-access/src/auth.api.ts, libs/app/auth/data-access/src/auth.module.ts, libs/app/core/src/core.routing.ts, libs/app/core/src/guards/route-guard.service.spec.ts, libs/app/core/src/guards/route-guard.service.ts
Implemented application-wide route guards based on AWS Cognito.
Fixes # 139-implement-routing-guards
- Added Route guard functionality.
- Added AuthService methods.
- Added tests for route guards.
- Added tests for AuthService.
- Jest Unit testing.
=> 139 implement routing guards

apps/api/src/main/java/com/fridgetoplate/controller/ProfileController.java, apps/api/src/main/java/com/fridgetoplate/frontendmodels/ProfileFrontendModel.java, apps/api/src/main/java/com/fridgetoplate/interfaces/Profile.java, apps/api/src/main/java/com/fridgetoplate/model/ProfileModel.java, apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java, apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java, libs/app/edit-recipe/feature/src/edit-recipe.page.ts
Bug Fix in Profile of GET request
Closes #191
=> 191 BUG Update Profile

libs/app/login/feature/src/login.page.html, libs/app/profile/data-access/src/profile.state.ts, libs/app/recipe/ui/src/recipe-card/recipe-card.component.html, libs/app/signup/feature/src/signup.page.html
Fixed small styling issues and a bug in the meal plan actions
Fixes #188 #189 
=> 188 bug cursor click sign up and login

libs/app/profile/data-access/src/profile.state.ts
=> 🐛 (app) Fixed Testing Bug

apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
Fixed the erroneous Update Profile Functionality
closes #200
=> BUG: Update Profile

apps/api/src/main/java/com/fridgetoplate/controller/MealPlanController.java, apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java, libs/app/home/feature/src/home.page.html, libs/app/navigation/feature/package.json, libs/app/navigation/feature/project.json, libs/app/navigation/feature/src/navigation.component.html, libs/app/navigation/feature/src/navigation.component.ts, libs/app/profile/feature/src/profile.page.html
Fixed profile styling error for profile picture.
=> 🐛 (app) Fixed Styling Error

apps/api/src/main/java/com/fridgetoplate/interfaces/ExtendedIngredient.java, apps/api/src/main/java/com/fridgetoplate/interfaces/Measures.java, apps/api/src/main/java/com/fridgetoplate/interfaces/Metric.java, apps/api/src/main/java/com/fridgetoplate/interfaces/SpoonacularRecipe.java, apps/api/src/main/java/com/fridgetoplate/interfaces/Us.java, apps/api/src/main/java/com/fridgetoplate/model/Ingredient.java, apps/api/src/main/java/com/fridgetoplate/service/ExternalApiService.java, apps/api/src/main/java/com/fridgetoplate/utils/SpoonacularRecipeConverter.java
Amended external API to allow units to show on frontend.
Fixes # 233
=> fix: :bug: Fixed no units on recipe page

libs/app/create/feature/src/create.page.spec.ts, libs/app/create/feature/src/create.page.ts
Added Limitations to image upload
Fixes # (242)
=> 242 bug user recipe picture

libs/app/profile/feature/src/profile.page.html
=> 249 uiux profile

apps/app-e2e/src/e2e/app.cy.ts, libs/app/create/feature/src/create.page.html, libs/app/create/feature/src/create.page.ts, libs/app/edit-recipe/feature/src/edit-recipe.page.html, libs/app/edit-recipe/feature/src/edit-recipe.page.ts, libs/app/recipe/feature/src/recipe.page.html, libs/app/recipe/ui/src/recipe-card/recipe-card.component.html, libs/app/recipe/utils/src/interfaces/recipe.interface.ts
Refactored the Create Recipe Page and Edit Recipe Page UI 
Fixes #250  (issue)
- [XI have added tests that prove my fix is effective or that my feature works
=> 250 uiux create

libs/app/explore/feature/src/explore.page.spec.ts, libs/app/explore/ui/src/searching-modal/searching-modal.component.spec.ts, libs/app/notifications/feature/src/notifications.page.html, libs/app/notifications/ui/src/tabbed/tabbed.component.html
Fixed UI/UX changes as discussed in Demo 4 Ui Analysis meeting.
Fixes # 254
=> 254 UI/ux notifications

libs/app/environments/utils/src/environment.ts, libs/app/recommend/data-access/src/recommend.api.ts, libs/app/recommend/utils/src/functions/index.ts, libs/app/recommend/utils/src/functions/recommendUtilFunctions.ts, libs/app/recommend/utils/src/index.ts, libs/app/recommend/utils/src/interfaces/index.ts, libs/app/recommend/utils/src/interfaces/product-information.interface.ts
* Created Recommend API Service for determining product information from barcode. 
* Integrated Go-UPC API.
* Added to environment variables.
* 
Fixes #235 
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] Any dependent …
=> 235 barcode creation

libs/app/create/feature/src/create.page.html, libs/app/create/feature/src/create.page.scss, libs/app/create/feature/src/create.page.spec.ts, libs/app/create/feature/src/create.page.ts
=> 231 add video upload to create recipe

libs/app/recipe/data-access/src/recipe.state.ts, libs/app/recipe/feature/src/recipe.page.html, libs/app/recipe/feature/src/recipe.page.spec.ts, libs/app/recipe/feature/src/recipe.page.ts, libs/app/review/feature/src/review.html, libs/app/review/feature/src/review.scss
Refactored recipe details page
Fixes #251
=> 251 uiux recipe 1

apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java, apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java, apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java, libs/app/profile/feature/src/profile.page.html, libs/app/profile/feature/src/profile.page.ts
Refactored the recipe service
Fixes #245
=> 245 recipe service refactor 3

apps/api/src/main/java/com/fridgetoplate/controller/ExploreController.java, apps/api/src/main/java/com/fridgetoplate/controller/MealPlanController.java, apps/api/src/main/java/com/fridgetoplate/controller/NotificationController.java, apps/api/src/main/java/com/fridgetoplate/controller/PreferencesController.java, apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java, apps/api/src/main/java/com/fridgetoplate/controller/RecommendController.java, apps/api/src/main/java/com/fridgetoplate/controller/ReviewController.java, apps/api/src/main/java/com/fridgetoplate/model/Ingredient.java, apps/api/src/main/java/com/fridgetoplate/model/IngredientModel.java, apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java, apps/api/src/main/java/com/fridgetoplate/repository/ReviewRepository.java, apps/api/src/main/java/com/fridgetoplate/service/ExploreService.java, apps/api/src/main/java/com/fridgetoplate/service/MealPlanService.java, apps/api/src/main/java/com/fridgetoplate/service/NotificationService.java, apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java, apps/api/src/main/java/com/fridgetoplate/service/RecommendService.java, apps/api/src/main/java/com/fridgetoplate/service/ReviewService.java
Refactored Review to use SOA . 
#290
=> Review Service Refactor

apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java, apps/api/src/main/java/com/fridgetoplate/model/RecipeDeleteResponseModel.java, apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java, libs/app/recipe/data-access/src/recipe.api.ts, libs/app/recipe/utils/src/interfaces/delete.recipe.response.ts
=> 257 bug error on recipe deletion

apps/app/src/styles.scss, apps/app/tailwind.config.js, libs/app/create/feature/src/create.page.html, libs/app/home/feature/src/home.page.html, libs/app/ingredient/ui/src/ingredient-card/ingredient-card.component.html
=> 301 uiux revised general application

libs/app/login/feature/src/login.page.html, libs/app/signup/feature/src/signup.page.html, libs/app/splash/ui/src/splash.page.html
Added Padding For Splash Screen
=> 237 create logo and splash screen

libs/app/create/feature/src/create.page.html, libs/app/edit-recipe/feature/src/edit-recipe.page.html
Fixed Create Page styling and restricted file uploads to images
closes #310
=> 296 uiux revised create

libs/app/recipe/feature/src/recipe.page.spec.ts, libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
=> 300 uiux revised recipe

apps/api/src/main/java/com/fridgetoplate/service/NotificationService.java, libs/app/core/src/core.module.ts, libs/app/explore/data-access/src/explore.module.ts, libs/app/explore/data-access/src/explore.state.ts, libs/app/explore/feature/src/explore.page.html, libs/app/explore/feature/src/explore.page.ts, libs/app/login/feature/src/login.page.ts, libs/app/recipe/ui/src/custom-skeleton-loader/custom-skeleton-loader.component.html, libs/app/signup/feature/src/signup.page.ts
Allow User To Search For Recipe
Fixes # (issue) 317 
=> 317 bug search page not showing results

libs/app/explore/feature/src/explore.page.html, libs/app/login/feature/src/login.page.ts, libs/app/signup/feature/src/signup.page.ts
Added a button to close the recent searches and changed Continue As Guest to navigate users to home page
Fixes #335 
=> ✨(app) added a button to close the search overlay

libs/app/login/feature/src/login.page.html, libs/app/notifications/feature/src/notifications.page.html, libs/app/signup/feature/src/signup.page.html
Top navbar fixed from covering content on signup, login and notifications for smaller desktop displays
Fixes #334
=> 334 top navbar covering content on signup and login

libs/app/profile/data-access/src/profile.state.ts, libs/app/profile/ui/src/shopping-list-modal/shoppinglist.component.html
Fixed the erroneous display of ingredients for meal plan shopping list when trying to view the shopping list for different days
=> Meal Plan Shopping List

libs/app/profile/feature/src/profile.page.html
Added Useful Information For New Users.
=> 325 profile add user feedback on empty saved and created recipes

libs/app/meal-plan/data-access/src/meal-plan.state.ts, libs/app/profile/data-access/src/profile.state.ts, libs/app/profile/feature/src/profile.page.spec.ts, libs/app/profile/feature/src/profile.page.ts, libs/app/review/feature/src/review.html
Fixed meal plan chart to auto refresh after its been updated
Fixes #344
=> 344 auto meal plan chart refresh

apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java, apps/api/src/main/java/com/fridgetoplate/service/ExploreService.java, apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java, apps/app/tailwind.config.js, libs/app/create/feature/src/create.page.html, libs/app/create/feature/src/create.page.spec.ts, libs/app/create/feature/src/create.page.ts, libs/app/edit-recipe/feature/src/edit-recipe.page.html, libs/app/edit-recipe/feature/src/edit-recipe.page.spec.ts, libs/app/edit-recipe/feature/src/edit-recipe.page.ts, libs/app/explore/feature/src/explore.page.html, libs/app/explore/feature/src/explore.page.ts, libs/app/home/feature/src/home.page.html, libs/app/home/feature/src/home.page.spec.ts, libs/app/home/feature/src/home.page.ts, libs/app/navigation/feature/src/navigation.component.html, libs/app/notifications/feature/src/notifications.page.html, libs/app/notifications/ui/src/tabbed/tabbed.component.html, libs/app/profile/feature/src/profile.page.html, libs/app/profile/ui/src/settings-modal/settings-modal.component.html, libs/app/recipe/feature/src/recipe.page.ts, libs/app/recipe/ui/src/recipe-card/recipe-card.component.html, libs/app/recommend/ui/src/item-edit-step/item-edit-step.html, libs/app/recommend/ui/src/item-edit-step/item-edit-step.spec.ts, libs/app/recommend/ui/src/item-edit-step/item-edit-step.ts, libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.html, libs/app/recommend/ui/src/recommend.module.ts, libs/app/recommend/ui/src/stepper-form/stepper-form.html, libs/app/recommend/utils/src/units.ts, libs/app/review/feature/src/review.component.ts
Added multiple UI/UX edits for ease of use as well as user feedback.
Fonts changed to "Inter"
Fixes # 326
=> 326 uiux aesthetic updates

libs/app/auth/data-access/src/auth.state.ts, libs/app/create/feature/src/create.page.spec.ts, libs/app/create/feature/src/create.page.ts, libs/app/edit-recipe/data-access/src/edit-recipe.state.ts, libs/app/preferences/data-access/src/preferences.api.ts, libs/app/preferences/data-access/src/preferences.state.ts, libs/app/profile/data-access/src/profile.api.ts, libs/app/profile/data-access/src/profile.state.ts, libs/app/recipe/data-access/src/recipe.state.ts, libs/app/recommend/data-access/src/recommend.state.ts, libs/app/review/feature/src/review.component.ts, libs/app/review/feature/src/review.spec.ts
Updated toast messages and restricted guest users from being able to add reviews 
Fixes #351
=> 351 update all error messages

libs/app/profile/ui/src/edit-modal/edit-modal.component.html, libs/app/profile/ui/src/edit-modal/edit-modal.component.spec.ts, libs/app/profile/ui/src/edit-modal/edit-modal.component.ts, libs/app/profile/ui/src/profile.module.ts
=> 345 add change profile pic

libs/app/explore/feature/src/explore.page.html
Added padding to explore page.
Fixes # 326
=> style: :lipstick: Added padding to explore page

libs/app/profile/data-access/src/profile.state.ts
Chart now initialized on profile data retrieval.
Fixes #368 
=> fix: :bug: Fixed chart initialization bug

libs/app/recipe/data-access/src/recipe.state.ts, libs/app/review/feature/src/review.component.ts, libs/app/review/feature/src/review.html, libs/app/review/feature/src/review.scss
Edited the review's adding functionality, delete icon, and look on the cards
Fixes #369
=> 369 edit reviews

libs/app/auth/data-access/src/auth.state.ts, libs/app/login/feature/src/login.page.html, libs/app/login/feature/src/login.page.ts, libs/app/profile/data-access/src/profile.state.ts, libs/app/signup/feature/src/signup.page.html, libs/app/signup/feature/src/signup.page.ts
Provided  feedback for users based on reason for unable to sign up, added form validation before signup and login.
Fixes #367
=> 367 bug sign up feedback

libs/app/auth/data-access/src/auth.state.ts, libs/app/auth/utils/src/auth.actions.ts, libs/app/profile/data-access/src/profile.api.ts, libs/app/profile/data-access/src/profile.state.ts, libs/app/profile/ui/src/edit-modal/edit-modal.component.html, libs/app/profile/ui/src/edit-modal/edit-modal.component.spec.ts, libs/app/profile/ui/src/edit-modal/edit-modal.component.ts
Fixed Update Profile error and Ensured the changed email also reflects on Cognito
Closes #364 
=> 364 bug change profile information

libs/app/create/feature/src/create.page.html, libs/app/edit-recipe/feature/src/edit-recipe.page.html, libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
Added Angular "numbers" pipe to facilitate rounding on recipe ratings and changed empty rating from "..." to "-"
Fixes #372 
=> 372 bug rating amount decimal places

libs/app/forgot/feature/src/forgot.page.html, libs/app/forgot/ui/src/confirm-modal/confirm-modal.component.html, libs/app/forgot/ui/src/verification-modal/verification-modal.component.html, libs/app/help/feature/src/help.page.html, libs/app/notifications/feature/src/notifications.page.html, libs/app/notifications/feature/src/notifications.page.scss, libs/app/profile/feature/src/profile.page.html, libs/app/recommend/ui/src/dropdown-select/dropdown-select.component.html, libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.html, libs/app/signup/feature/src/signup.page.html, libs/app/unauthorised/feature/src/unauthorised.page.html
Updated Dark Mode To Many Pages In Application
=> 365 bug dark mode
